name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Super-Linter
      # You may pin to the exact commit or the version.
      # uses: super-linter/super-linter@b92721f792f381cedc002ecdbb9847a15ece5bb8
        uses: super-linter/super-linter@v7.1.0
          
