name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: ESLint (JS/TS) Action 
      # You may pin to the exact commit or the version.
      # uses: iCrawl/action-eslint@ff2a58dcbc1aaec51815d58e8bf70962c4f2b557
        uses: iCrawl/action-eslint@v1
